on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  publish-project-provider:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
      
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          build-root-directory: gradle-project-provider
      
      - name: Execute Installation Build
        run: |
          cd gradle-project-provider
          ./gradlew :project-provider:distTar

      - name: Releasing jar
        uses: softprops/action-gh-release@v1
        with:
          files: gradle-project-provider/project-provider/build/distributions/*.tgz
