name: CI-check

on:
  workflow_dispatch:
  push:
    branches-ignore: 
      - main
      - release/**

jobs:
  build-distribution:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Build and upload distribution
        uses: ./.github/actions/build-dist

  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Configure Gradle
        uses: gradle/gradle-build-action@v3
      - name: Run project provider tests
        run: |
          cd gradle-project-provider
          ./gradlew test
      - name: Run task avoidance tests
        run: |
          npm install
          npm run format-check & npm run lint && npm run test
        working-directory: github-actions-task-avoidance

  action-inputs:
    needs: build-distribution
    uses: ./.github/workflows/integ-test-action-inputs.yml
    with:
      runner-os: '["ubuntu-latest"]'
      download-dist: true
